name: Autoclose
on:
  issues:
    types: opened
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose issues that do not follow issue template in title
      uses: IndyV/IssueChecker@v1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-close-message: "@${issue.user.login} your issue was automatically closed because it didn't follow the [issue template](https://raw.githubusercontent.com/Cxbx-Reloaded/game-compatibility/master/.github/ISSUE_TEMPLATE/compatibility-report.md).\n\nPlease read the [Issue/Report Guidelines](https://github.com/Cxbx-Reloaded/game-compatibility#issue-titles)."
        issue-pattern: '^((?!(\[[A-Za-z0-9]{2}-[A-Za-z0-9]{3}\]) (\[*.*\])).)*$'
